### ISSUE TITLE
 Dear author, I would like to ask a question about the data set？

### ISSUE THREAD

**Issue by Jinn02-25** [YuWVandy/DPGNN#1]
In the process of running the code, I found that the DE, EN, ES....
I don’t know which data sets these names replace.
Could you please answer in your busy schedule?

**Comment by yuwvandy** [comment]
Thanks for your interest in our work and sorry for not being clear. So DE, EN, ES... are datasets from Twitch, which are gamer networks where nodes represent gamers and edges are followerships. Here the link includes a detailed description of each of these datasets.  https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/twitch.html#Twitch


Please let me know any further questions you may have.

**Comment by Jinn02-25** [comment]
thank you for your answer！！
After reading your paper, I set up an environment to reproduce the experiment, which provided a lot of help for my next stage of study. Thanks

**Comment by Jinn02-25** [comment]
Then I would like to ask you, because you used the encoding and decoding method, and got multiple outputs after decoding. I want to compare the classification results of your model with the tsne visualization of other models, but I can’t get it. What should I do?

Because the tsne tutorial I found on the Internet is only a single output relatively simple, I look forward to your reply！

**Comment by yuwvandy** [comment]
Hi Jinn, very appreciate your interest in our work and am also glad that I can help you.

For you next question, since this work utilizes a 2-layer GCN backbone as the encoder and after getting the embedding of each node from this 2-layer GCN, we further calculate distance embedding. So I think in order to apply TSNE visualization, we can simply take the embedding output by 2-layer GCN here, which is particularly obtained at script model 'GCN' function. Besides, if you further want to compare the distance embedding, you can further after 'dist_embed' and 'prototype' to get the dist_embedding.

Let me know any help I can further assist any time! Keep contact.

**Comment by Jinn02-25** [comment]
ok thanks for your reply！

**Comment by Jinn02-25** [comment]
>
