### ISSUE TITLE
Looking forward to your reply!!

### ISSUE THREAD

**Issue by Jinn02-25** [YuWVandy/DPGNN#2]
Hello Dr. Wang, I am re-reading your paper intensively. I have encountered some problems in the explanation part of formula (9). I would like to ask you to solve confusion.

1.“computes the inverse ratio of the number of labeled nodes in the node 𝑣𝑖’s class 𝜙(𝑣𝑖),Í𝑣𝑗∈V𝑙Y𝑗𝜙(𝑣𝑖), to the total number of labeled nodes |V𝑙|.”My colleagues have different perceptions of this sentence, We want to know what exactly Í𝑣𝑗∈V𝑙Y𝑗𝜙(𝑣𝑖) stands for?

2.why  |V𝑙| and Í𝑣𝑗∈V𝑙Y𝑗𝜙(𝑣𝑖) are inversely ratio, Shouldn't they be proportional when the weighting factors are given?

3.Then this part also talks about the network homogeneity can expand the training data, I would like to ask you whether it is achieved by formula 12?

Sorry to bother you, looking forward to your reply!!

**Comment by Jinn02-25** [comment]
Second, you defined C={1, 2,...,C} earlier as a collection of classes，node 𝑣𝑖’s class 𝜙(𝑣𝑖)，mean the same thing?

**Comment by Jinn02-25** [comment]
Second, you defined C={1, 2,...,C} earlier as a collection of classes，node 𝑣𝑖’s class 𝜙(𝑣𝑖)，mean the same thing?

**Comment by yuwvandy** [comment]
Hi Jinn,
 Thanks for your interest in our paper and sorry for causing such confusion due to my unconcise math notations. Regarding your questions:
  1. The first question is basically what Eq. (9) does and what \mathbf{Y}_{j\phi{v_i}} stands for. Basically, our label for each node is defined as the one-hot encoding vector \mathbf{Y} and if we want to know the total number of labeled nodes in the class (say class c), we need to go over all labeled nodes in the labeled node-set $v_j\in\mathcal{V}_l$ and check whether \mathbf{Y}_{jc} = 1 (here the first index represents the node $v_j$ and the second index c represents the corresponding class). And in that equation (9), the class c we are interested in is exactly \phi{v_i}.  Let me further take a simple example here to help explain. Say we have three labeled nodes \mathcal{V}_l = {v_1, v_2, v_3} with their classes to be class 1, 2, 2 (assume the total number of classes are 3 ), then |\mathcal{V}_l| = 3 and the one-hot encoding matrix $\mathbf{Y} = [1, 0, 0; 0, 1, 0; 0, 1, 0]$, then when we look at the first node v_1, $\phi_{v_1} = 1$ and the denominator would go through every labeled nodes $v_j$ and check there corresponding $\mathbf{Y}_{j1}$, which means we count the total number of labeled nodes in class 1 and in this case we have only one labeled node in class 1, so the denominator would be 1. And then the numerator is 3, so that ratio for this node would be 3/1 = 3. Similarly, for nodes 2 and 3, the ratio would be 3/2. Then we can easily see the total number of information is balanced among different classes here (class 1 only has one node but its weight is 3, class 2 has two nodes but its weight is 3/2).

2. I didn't quite get your second question. Here the main reason is that when we do label propagation for imbalanced datasets, it's highly possible that we propagate more on majority classes while less on minority classes, therefore, we should multiply it by the inverse of the class ratio.
3. Yeah exactly. Based on network homophily, birds of the same feather often fly together (nodes are closer to each other in networks that often share the similarity feature distributions or labels), therefore we could leverage the label propagation to augment our training data.

4. Regarding your second post, yeah I need a math notation here to tell us given this labeled node, what its class or label is. So $\phi(v_i) \in \{1,2...,C\}$

Really hope the above answers would help solve some of your confusion but definitely keep posting if you have more questions. Willing to offer my help!😊

**Comment by Jinn02-25** [comment]
Dr. Wang，very grateful for your help, your reply solved our confusion and the example given by Equation 9 is very vivid！
Once again to express my sincere thanks to you, wish you a happy life!
